# Generated by Django 5.0.4 on 2024-04-27 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bun_Store', '0002_customer_date_creation_customer_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='last_name',
        ),
    ]
