# Generated by Django 5.0.4 on 2024-04-27 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bun_Store', '0004_customer_first_name_customer_last_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
