# Generated by Django 5.0.4 on 2024-04-28 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bun_Store', '0004_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='zip',
            new_name='zipcode',
        ),
    ]
