# Generated by Django 5.0.4 on 2024-04-27 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bun_Store', '0007_remove_customer_first_name_remove_customer_last_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
