# Generated by Django 5.0.4 on 2024-05-19 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bun_Store', '0007_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='offer',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
